version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
    nodejs: "22"
  jobs:
    build:
      html:
        - pip install --upgrade -r docs/requirements.txt
        - cd docs && jupyter book build --html --strict
    post_build:
      - mkdir --parents $READTHEDOCS_OUTPUT/html/
      - cp --recursive docs/_build/html/* $READTHEDOCS_OUTPUT/html/

formats: []
