name: echodataflow
channels:
  - conda-forge
  - defaults
dependencies:
  - boto3
  - cartopy
  - echopype
  - ipykernel
  - geopandas
  - geopy
  - opencv  # this should be specified in hakeML
  - openpyxl  # for reading xlsx
  - prefect
  - python=3.12
  - shapely
  - pip:
    - prefect[shell]
    - prefect[dask]