init:
  counter_raw_copy: 0
  flow_start_time: "20230804T155000"
ingest_haul:
  interval: 5
  date_prefix: "202407"
  species_code: 22500
  path_main: "/Users/wujung/code_git/echodataflow/temp_bio"
  path_bio_files: "agr230002-bucket01/prefect_test/temp_bio/bio_csv"
  cred_file: "/Users/wujung/.config/rclone/rclone.conf"
  file_haul_info_all: haul_info_all.csv
  file_specimen_all: specimen_all.csv
  file_length_all: length_all.csv
  file_length_count_all: length_count_all.csv
  file_stratum_mean: stratum_mean.csv
ingest_NASC:
  interval: 5
  path_main: "/Users/wujung/code_git/echodataflow/temp_bio"
  path_NASC_files: "agr230002-bucket01/prefect_test/temp_bio/nasc_zarr"
  cred_file: "/Users/wujung/.config/rclone/rclone.conf"
  file_NASC_all: NASC_all.csv
  file_stratum_mean: stratum_mean.csv
  file_NASC_all_grid: NASC_all_griddify.geojson
  num_NASC_reprocess: 1
update_grid:
  path_main: "/Users/wujung/code_git/echodataflow/temp_bio"
  file_NASC_all_grid: NASC_all_griddify.geojson
  file_stratum_mean: stratum_mean.csv
  file_grid_cells: grid_cells.geojson