init:
  counter_raw_copy: 0
  flow_start_time: "20230804T153000"
copy_raw:
  interval: 2
raw2Sv:
  interval: 5
create_MVBS:
  interval: 10
  slice_mins: 10
  num_slices: 3
predict_hake:
  interval: 10
  slice_mins: 10
  num_slices: 3
  temperature: 0.5