init:
  counter_raw_copy: 0
  flow_start_time: "20250610T180000" # "20230804T155000"  # "20250308T001256"
copy_raw:
  interval: 2
raw2Sv:
  interval: 5
  parallel: False
  encode_mode: power
  waveform_mode: CW
  depth_offset: 9.5
  sonar_model: EK80
  nmea_sentence: GGA
  path_raw: "/Users/feresa/mnt_qnap/Acoustics/EK80_raw/WJ"
  path_main: "/Volumes/sh2506_ext1/WJ_test"
  file_Sv_csv: Sv_files.csv
create_MVBS:
  interval: 10
  slice_mins: 10
  num_slices: 3
  path_main: "/Volumes/sh2506_ext1/WJ_test"
  file_Sv_csv: Sv_files.csv
  file_MVBS_csv: MVBS_files.csv
predict_hake:
  interval: 10
  slice_mins: 10
  num_slices: 3
  temperature: 0.5
  softmax_threshold: 0.5
  path_main: "/Volumes/sh2506_ext1/WJ_test"
  file_MVBS_csv: MVBS_files.csv
  file_prediction_csv: prediction_files.csv
# compute_NASC:
#   interval: 10
#   slice_mins: 10
#   num_slices: 3
#   softmax_threshold: 0.5
file_upload:
  interval: 10
  src_dir: "/Volumes/sh2506_ext1/WJ_test"
  dest_dir: "osn_sdsc_hake:/agr230002-bucket01/prefect_sh2506/leg1"
  exclude_subdirs:
    - Sv
