init:
  counter_raw_copy: 0
  flow_start_time: "2025-06-13T02:00:00+00:00"  # use ISO8601 format: if UTC use +00:00 or Z
  # "2025-06-12T20:19:00-07:00"  # use ISO8601 format: if UTC use +00:00 or Z
  # "20230804T155000"  # "20250308T001256"
copy_raw:
  interval: 2
raw2Sv:
  interval: 5
  parallel: False
  encode_mode: power
  waveform_mode: CW
  depth_offset: 9.5
  sonar_model: EK80
  nmea_sentence: GGA
  path_raw: "/Users/feresa/mnt_qnap/Acoustics/EK80_raw/Leg 1"
  path_main: "/Volumes/sh2506_ext1/leg1_test"
  file_Sv_csv: Sv_files.csv
create_MVBS:
  interval: 10
  slice_mins: 10
  num_slices: 3
  path_main: "/Volumes/sh2506_ext1/leg1_test"
  file_Sv_csv: Sv_files.csv
  file_MVBS_csv: MVBS_files.csv
predict_hake:
  interval: 20
  slice_mins: 40
  num_slices: 3
  temperature: 0.5
  softmax_threshold: 0.5
  path_main: "/Volumes/sh2506_ext1/leg1_test"
  file_MVBS_csv: MVBS_files.csv
  file_prediction_csv: prediction_files.csv
file_upload_acoustics:
  interval: 10
  src_dir: "/Volumes/sh2506_ext1/leg1_test"
  dest_dir: "osn_sdsc_hake:/agr230002-bucket01/prefect_sh2506_test/acoustics"
  exclude_subdirs:
    - Sv
# file_upload_trawl:
#   interval: 10
#   src_dir: "/Volumes/sh2506_ext1/WJ_test"
#   dest_dir: "osn_sdsc_hake:/agr230002-bucket01/prefect_sh2506/trawl"
#   exclude_subdirs:
#     - Sv
#     - MVBS
#     - prediction
