init:
  counter_raw_copy: 0
  flow_start_time: "2025-07-04T16:13:00+00:00"
  # "2025-06-13T11:45:00+00:00"  # use ISO8601 format: if UTC use +00:00 or Z
  # "20230804T155000"  # "20250308T001256"
# copy_raw:
#   interval: 2
#   path_raw_txt: "/Users/wujung/code_git/echodataflow/temp_data/SH2306_raw_files.txt"  # list of raw files in S3
#   path_s3: "data/raw/Bell_M._Shimada/SH2306/EK80"  # S3 path for raw files
#   path_copy: "/Users/wujung/code_git/echodataflow/temp_data/raw"  # path to copy raw data to
raw2Sv:
  interval: 5
  exclude_before: "2025-06-17T20:00:00+00:00" # "2025-06-13T10:00:00+00:00"  # use ISO8601 format: if UTC use +00:00 or Z
  parallel: False
  encode_mode: power
  waveform_mode: CW
  depth_offset: 7
  sonar_model: EK80
  nmea_sentence: GGA
  filename_pattern: "IWCPS*.raw"
  path_raw: "/Users/feresa/mnt_qnap/Leg 2"
  path_main: "/Volumes/sh2506_ext1/leg2"
  file_Sv_csv: Sv_files.csv
create_MVBS:
  interval: 10
  slice_mins: 20
  num_slices: 3
  path_main: "/Volumes/sh2506_ext1/leg2"
  file_Sv_csv: Sv_files.csv
  file_MVBS_csv: MVBS_files.csv
predict_hake:
  interval: 20
  slice_mins: 40
  num_slices: 3
  temperature: 0.5
  softmax_threshold: 0.5
  path_main: "/Volumes/sh2506_ext1/leg2"
  file_MVBS_csv: MVBS_files.csv
  file_prediction_csv: prediction_files.csv
file_upload_acoustics:
  interval: 10
  src_dir: "/Volumes/sh2506_ext1/leg2"
  dest_dir: "osn_sdsc_hake:/agr230002-bucket01/prefect_sh2506_test/acoustics"
  exclude_subdirs:
    - Sv
  max_age: 2
file_upload_trawl:
  interval: 10
  src_dir: "/Users/feresa/mnt_qnap_clams/nwc"
  dest_dir: "osn_sdsc_hake:/agr230002-bucket01/prefect_sh2506_test/trawl"
  exclude_subdirs:
    - backups
    - "temp AB stuff"
    - "How to run CLAMS reports.docx"
  max_age: -1
