init:
  counter_raw_copy: 0
  flow_start_time: # "2025-06-13T11:45:00+00:00"  # use ISO8601 format: if UTC use +00:00 or Z
ingest_haul:
  interval: 5
  date_prefix: "202407"
  species_code: 22500
  path_main: "/media/volume/shimada_202506_volume/trawl" # path to local processed trawl info
  path_bio_files: "agr230002-bucket01/prefect_sh2506_test/trawl" # path to cloud trawl data
  cred_file: "/home/exouser/.config/rclone/rclone.conf"
  file_haul_info_all: haul_info_all.csv
  file_specimen_all: specimen_all.csv
  file_length_all: length_all.csv
  file_length_count_all: length_count_all.csv
  file_stratum_mean: stratum_mean.csv
ingest_NASC:
  interval: 5
  path_main: "/media/volume/shimada_202506_volume/NASC" # path to local integrated data
  path_trawl: "/media/volume/shimada_202506_volume/trawl" # path to local trawl info
  path_NASC_files: "agr230002-bucket01/prefect_sh2506_test/acoustics/NASC" # path to cloud acoustic data
  cred_file: "/home/exouser/.config/rclone/rclone.conf"
  file_NASC_all: NASC_all.csv
  file_stratum_mean: stratum_mean.csv
  file_NASC_all_grid: NASC_all_griddify.geojson
  num_NASC_reprocess: 1
update_grid:
  path_main: "/Users/feresa/code_git/echodataflow/temp_bio"
  file_NASC_all_grid: NASC_all_griddify.geojson
  file_stratum_mean: stratum_mean.csv
  file_grid_cells: grid_cells.geojson
update_cache_MVBS:
  interval: 10
  slice_mins: 180
  path_cache: "/media/volume/shimada_202506_volume/viz_data_cache"
  path_MVBS: "agr230002-bucket01/prefect_sh2506_test/acoustics/MVBS"
  cred_file: "/home/exouser/.config/rclone/rclone.conf"
  file_MVBS_csv: MVBS_files.csv
  file_MVBS_zarr: latest_MVBS.zarr
