from pkg_resources import DistributionNotFound, get_distribution

from . import echodataflow_cli
from .models.datastore import StorageType
from .stages.echodataflow import (echodataflow_config_AWS,
                                       echodataflow_config_AZ_cosmos,
                                       echodataflow_create_prefect_profile,
                                       echodataflow_start, get_active_profile,
                                       load_profile)
from .utils.config_utils import extract_fs, glob_url
from .utils.file_utils import get_ed_list, get_last_run_output, get_zarr_list
from .docker_trigger import docker_trigger
from .utils.filesystem_utils import load_block

try:
    VERSION = get_distribution(__name__).version
except DistributionNotFound:  # pragma: no cover
    try:
        from .version import version as VERSION  # noqa
    except ImportError:  # pragma: no cover
        raise ImportError(
            "Failed to find (autogenerated) version.py. "
            "This might be because you are installing from GitHub's tarballs, "
            "use the PyPI ones."
        )
__version__ = VERSION

__all__ = [
    "echodataflow_start",
    "echodataflow_create_prefect_profile",
    "load_profile",
    "echodataflow_config_AWS",
    "echodataflow_config_AZ_cosmos",
    "get_active_profile",
    "StorageType",
    "load_block",
    "echodataflow_cli",
    "extract_fs", 
    "glob_url",
    "get_last_run_output",
    "get_ed_list", 
    "get_zarr_list",
    "docker_trigger"
]
