active_recipe: target_strength 
use_local_dask: true
n_workers: 5
pipeline:
- recipe_name: target_strength
  stages:
  - name: echodataflow_open_raw
    module: echodataflow.stages.subflows.open_raw
    options:
      save_raw_file: true
      use_raw_offline: true
      use_offline: true
  - name: echodataflow_compute_TS
    module: echodataflow.stages.subflows.compute_TS
    options:
      use_offline: true