from pkg_resources import DistributionNotFound, get_distribution
from .stages.subflows.echoflow import (
    echoflow_start,
    echoflow_create_prefect_profile,
    load_profile,
    echoflow_config_AWS,
    echoflow_config_AZ_cosmos,
    get_active_profile,
)
from .config.models.datastore import StorageType
from .stages.utils.config_utils import load_block


try:
    VERSION = get_distribution(__name__).version
except DistributionNotFound:  # pragma: no cover
    try:
        from .version import version as VERSION  # noqa
    except ImportError:  # pragma: no cover
        raise ImportError(
            "Failed to find (autogenerated) version.py. "
            "This might be because you are installing from GitHub's tarballs, "
            "use the PyPI ones."
        )
__version__ = VERSION

__all__ = [
    "echoflow_start",
    "echoflow_create_prefect_profile",
    "load_profile",
    "echoflow_config_AWS",
    "echoflow_config_AZ_cosmos",
    "get_active_profile",
    "StorageType",
    "load_block"
]
