name: Release Docker Image
on:
  release:
    types: [published]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Build the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:${{ github.sha }}

    # Log in to Docker Hub (you need to set up DOCKER_USERNAME and DOCKER_PASSWORD in GitHub Secrets)
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Push the Docker image to Docker Hub
    - name: Push the Docker image
      run: docker push my-image-name:${{ github.sha }}
